services:
  magic-platform:
    image: magic-rj92
    env_file:
      - .env.dev
    command: /app/run_app.sh mage start $PROJECT_NAME
    ports:
      - 6789:6789
    volumes:
      - .:/$MAGE_CODE_PATH
      - ~/.mage_data:/$MAGE_CODE_PATH/mage_data
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    restart: on-failure:5
    networks:
      - app-network
    depends_on:
      - magic-database
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 4096M
  magic-database:
    image: pgvector/pgvector:0.6.0-pg16
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres/data:/var/lib/postgresql/data
      - ./scripts/database:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-network
  mlflow:
    image: mlflow-aws-rj92
    env_file:
      - .env.dev
    ports:
      - 5000:5000
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://mlflow-bucket/ --host 0.0.0.0
    depends_on:
      - minio
      - localstack
    volumes:
      - ./mlflow_db:/app/mlflow
    networks:
      - app-network
  minio:
    image: minio/minio
    command: server /data --console-address ":9001" --address ":9000" 
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env.dev
    volumes:
      - ./minio-local-artifacts:/data
    networks:
      - app-network
  localstack:
    image: localstack/localstack-pro
    ports:
      - 4566:4566
    env_file:
      - .env.dev
    volumes:
      - ./s3-local-artifacts:/var/lib/localstack
    networks:
      - app-network
networks:
  app-network:
    driver: bridge