[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring"]

[tool.black]
line-length = 80
target-version = ['py312']

[tool.isort]
multi_line_output = 3
length_sort = true
force_single_line = true
