name: Auto Merge Pull Request

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --merge --admin
